name: '🦄 🌈  Formula: Video'
description: 'Provides a Video paragraph type wired to the dk_start_theme SDC video component.'
type: 'Paragraphs'

recipes:
  - formula-paragraphs

config:
  strict: false
