<?php

/**
 * @file
 * Validates all CSS & JS files referenced in greg_site_theme.libraries.yml exist.
 *
 * This script is used in GitLab CI to ensure the build-assets job successfully
 * generated all required files. It parses the libraries YAML file and checks
 * for the existence of each CSS and JS file path.
 *
 * Exit codes:
 * - 0: All files exist
 * - 1: One or more files are missing
 * - 2: Error reading or parsing libraries file
 */

// Ensure we're running from the theme root.
$themeRoot = dirname(__DIR__);
$librariesFile = $themeRoot . '/greg_site_theme.libraries.yml';

if (!file_exists($librariesFile)) {
  fwrite(STDERR, "ERROR: Could not find greg_site_theme.libraries.yml at: {$librariesFile}\n");
  exit(2);
}

// Use Symfony YAML component - check multiple locations.
$autoloadPaths = [
// CI isolated composer install.
  '/tmp/validator/vendor/autoload.php',
  $themeRoot . '/vendor/autoload.php',
  $themeRoot . '/../../core/vendor/autoload.php',
  dirname(__DIR__, 4) . '/vendor/autoload.php',
];

$autoloadFound = FALSE;
foreach ($autoloadPaths as $autoloadPath) {
  if (file_exists($autoloadPath)) {
    require_once $autoloadPath;
    $autoloadFound = TRUE;
    break;
  }
}

if (!$autoloadFound) {
  fwrite(STDERR, "ERROR: Could not find Composer autoload.php. Tried:\n");
  foreach ($autoloadPaths as $path) {
    fwrite(STDERR, "  - {$path}\n");
  }
  exit(2);
}

use Symfony\Component\Yaml\Yaml;

try {
  $libraries = Yaml::parseFile($librariesFile);
}
catch (Exception $e) {
  fwrite(STDERR, "ERROR: Failed to parse {$librariesFile}: " . $e->getMessage() . "\n");
  exit(2);
}

$missingFiles = [];
$checkedFiles = [];

foreach ($libraries as $libraryName => $libraryConfig) {
  if (!is_array($libraryConfig)) {
    continue;
  }

  // Check CSS files.
  if (isset($libraryConfig['css']) && is_array($libraryConfig['css'])) {
    foreach ($libraryConfig['css'] as $category => $files) {
      if (!is_array($files)) {
        continue;
      }
      foreach ($files as $filePath => $options) {
        // Skip external files (URLs)
        if (preg_match('#^https?://#', $filePath)) {
          continue;
        }

        $checkedFiles[$filePath] = $checkedFiles[$filePath] ?? [];
        $checkedFiles[$filePath][] = $libraryName;

        $absolutePath = $themeRoot . '/' . $filePath;
        if (!file_exists($absolutePath)) {
          $missingFiles[$filePath] = $missingFiles[$filePath] ?? [];
          $missingFiles[$filePath][] = $libraryName;
        }
      }
    }
  }

  // Check JS files.
  if (isset($libraryConfig['js']) && is_array($libraryConfig['js'])) {
    foreach ($libraryConfig['js'] as $filePath => $options) {
      // Skip external files (URLs)
      if (preg_match('#^https?://#', $filePath)) {
        continue;
      }

      $checkedFiles[$filePath] = $checkedFiles[$filePath] ?? [];
      $checkedFiles[$filePath][] = $libraryName;

      $absolutePath = $themeRoot . '/' . $filePath;
      if (!file_exists($absolutePath)) {
        $missingFiles[$filePath] = $missingFiles[$filePath] ?? [];
        $missingFiles[$filePath][] = $libraryName;
      }
    }
  }
}

// Report results.
$totalChecked = count($checkedFiles);
$totalMissing = count($missingFiles);

echo "Validation Results:\n";
echo "==================\n\n";
echo "Total files checked: {$totalChecked}\n";
echo "Missing files: {$totalMissing}\n\n";

if ($totalMissing > 0) {
  echo "ERROR: The following files are referenced in greg_site_theme.libraries.yml but do not exist:\n\n";

  foreach ($missingFiles as $filePath => $libraries) {
    echo "  ✗ {$filePath}\n";
    echo "    Referenced by libraries: " . implode(', ', array_unique($libraries)) . "\n\n";
  }

  echo "These files should be generated by the build process (npm run build).\n";
  echo "If you see this error in CI, the build-assets job may have failed.\n";
  echo "If you see this locally, run: npm install && npm run build\n";

  exit(1);
}

echo "✓ All files referenced in greg_site_theme.libraries.yml exist!\n";
exit(0);
