#!/bin/bash
#
# Validates that all CSS and JS files referenced in dk_start_theme.libraries.yml exist.
# Used in GitLab CI to ensure the build-assets job successfully generated all required files.
#
# Exit codes:
# - 0: All files exist
# - 1: One or more files are missing

set -e

THEME_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIBRARIES_FILE="${THEME_ROOT}/dk_start_theme.libraries.yml"

if [ ! -f "$LIBRARIES_FILE" ]; then
  echo "ERROR: Could not find dk_start_theme.libraries.yml at: ${LIBRARIES_FILE}" >&2
  exit 2
fi

echo "Validation Results:"
echo "=================="
echo ""

# Extract file paths from YAML (skip external URLs and src directories)
# Look for lines with .css: or .js: that don't start with http
FILES=$(grep -E '^\s+.*\.(css|js):' "$LIBRARIES_FILE" | \
        grep -v 'https\?://' | \
        awk -F: '{print $1}' | \
        sed 's/^[[:space:]]*//' | \
        grep -v '/src/' | \
        sort -u)

TOTAL=0
MISSING=0
MISSING_FILES=""

for FILE in $FILES; do
  TOTAL=$((TOTAL + 1))
  FULL_PATH="${THEME_ROOT}/${FILE}"
  
  if [ ! -f "$FULL_PATH" ]; then
    MISSING=$((MISSING + 1))
    MISSING_FILES="${MISSING_FILES}\n  ✗ ${FILE}"
  fi
done

echo "Total files checked: ${TOTAL}"
echo "Missing files: ${MISSING}"
echo ""

if [ $MISSING -gt 0 ]; then
  echo "ERROR: The following files are referenced in dk_start_theme.libraries.yml but do not exist:"
  echo -e "${MISSING_FILES}"
  echo ""
  echo "These files should be generated by the build process (npm run build)."
  echo "If you see this error in CI, the build-assets job may have failed."
  echo "If you see this locally, run: npm install && npm run build"
  exit 1
fi

echo "✓ All files referenced in dk_start_theme.libraries.yml exist!"
exit 0
