name: '🦄 🌈  Formula: Tabs Content Item'
description: 'Child paragraph for the tabs-content component. Rendered via embed of the dk_start_theme SDC tabs-content component.'
type: 'Paragraphs'

recipes:
  - formula-paragraphs

config:
  strict: false
