#!/bin/bash
## Description: Capture Playwright VRT baseline screenshots.
## Usage: test:vrt:baseline [flags] [args]
## Example: "test:vrt:baseline"
## Example: "test:vrt:baseline --last-failed"
## Example: "BASE_URL=https://dk-start.ddev.site test:vrt:baseline"
## Example: "BASE_URL=\"https://dev-dk-start.pantheonsite.io/}\" test:vrt:baseline"
cd "${DDEV_APPROOT}/tests/playwright"
npm run test:vrt:baseline -- $@
