name: '🦄 🌈  Formula: Accordion Item'
description: 'Child paragraph for the accordion component. Rendered via embed of the dk_start_theme SDC accordion component.'
type: 'Paragraphs'

recipes:
  - formula-paragraphs

config:
  strict: false
