<?php

/**
 * @file
 * This is a Drupal 11 settings.ddev.php file automatically generated by DDEV.
 *
 * DDEV manages this file and may delete or overwrite it unless this
 * comment, marked with #ddev-generated, is removed. It is recommended
 * that you leave this file alone.
 */

$host = "db";
$port = 3306;
$driver = "mysql";

$databases['default']['default']['database'] = "db";
$databases['default']['default']['username'] = "db";
$databases['default']['default']['password'] = "db";
$databases['default']['default']['host'] = $host;
$databases['default']['default']['port'] = $port;
$databases['default']['default']['driver'] = $driver;

$databases['migrate']['default'] = [
  'database' => 'migrate',
  'username' => 'root',
  'password' => 'root',
  'host' => 'db',
  'port' => '3306',
  'driver' => 'mysql',
  'namespace' => 'Drupal\mysql\Driver\Database\mysql',
];

$settings['hash_salt'] = '5690f07b27f8def452809fd420c4eb2c7fb058feaeb604b3123dee7c89e14d6c';

$settings['config_sync_directory'] = '../config/sync';

// This will prevent Drupal from setting read-only permissions on sites/default.
$settings['skip_permissions_hardening'] = TRUE;

// This will ensure the site can only be accessed through the intended host
// names. Additional host patterns can be added for custom configurations.
$settings['trusted_host_patterns'] = ['.*'];

// Override drupal/symfony_mailer default config to use Mailpit.
$config['symfony_mailer.settings']['default_transport'] = 'smtp_ddev';

// Enable verbose logging for errors.
// https://www.drupal.org/forum/support/post-installation/2018-07-18/enable-drupal-8-backend-errorlogdebugging-mode
$config['system.logging']['error_level'] = 'verbose';

// Local development services
$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/development.services.yml';

// Disable caching for development.
$settings['cache']['bins']['render'] = 'cache.backend.null';
$settings['cache']['bins']['page'] = 'cache.backend.null';
$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';
$settings['cache']['bins']['discovery'] = 'cache.backend.null';

// Allow rebuilding cache via /rebuild.php without authentication.
$settings['rebuild_access'] = TRUE;

// Enable Twig development mode.
$settings['twig_debug'] = TRUE;

// Disable CSS and JS aggregation for easier debugging.
$config['system.performance']['css']['preprocess'] = FALSE;
$config['system.performance']['js']['preprocess'] = FALSE;

// Stage file proxy settings.
// $config['stage_file_proxy.settings']['origin'] = 'https://test-lapl.pantheonsite.io';

// Environment indicator
$config['environment_indicator.indicator']['name'] = 'DDEV';
$config['environment_indicator.indicator']['bg_color'] = '#f5792a';

// Search API.
// Search indexes should default to `pantheon_search` server.
$config['search_api.server.pantheon_search']['status'] = FALSE;
// $config['search_api.index.YOUR_INDEX']['server'] = 'local';

// Exclude modules from config sync.
$settings['config_exclude_modules'] = [
  'devel',
  'devel_entity_updates',
  'stage_file_proxy',
  'upgrade_status',
];

// Redis caching — enabled via REDIS_ENABLED env var, set by setup-pantheon
// after the redis module has been installed by the formula-pantheon recipe.
if (!defined('MAINTENANCE_MODE') && getenv('REDIS_ENABLED') === 'true') {
  $settings['redis.connection']['interface'] = 'PhpRedis';
  $settings['redis.connection']['host'] = 'redis';
  $settings['cache']['default'] = 'cache.backend.redis';
  $settings['container_yamls'][] = DRUPAL_ROOT . '/modules/contrib/redis/example.services.yml';
}

// Override a key locally.
// $config['key.key.YOUR_KEY']['key_provider_settings']['file_location'] = 'private://keys/somekey.key';

// Override config example.
// $config['your_module.settings']['some_key'] = 'value';

