name: '🦄 🌈  Formula: Alerts'
description: 'Provides a Alerts paragraph type wired to the dk_start_theme SDC alert component.'
type: 'Paragraphs'

recipes:
  - formula-paragraphs

config:
  strict: false
