#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/ddev/ddev-drupal-contrib
## Description: Run eslint inside the web container
## Usage: eslint [flags] [args]
## Example: "ddev eslint"
## ExecRaw: true

set -eu -o pipefail

if "$DDEV_DOCROOT/core/node_modules/.bin/eslint" --version >/dev/null ; then
  # Change directory to the theme folder
  cd "${DDEV_COMPOSER_ROOT}/${THEME_PATH}" || exit
  "$DDEV_DOCROOT/core/node_modules/.bin/eslint" --config="$DDEV_DOCROOT/core/.eslintrc.passing.json" --no-error-on-unmatched-pattern --ignore-pattern="*.es6.js" --resolve-plugins-relative-to=$DDEV_DOCROOT/core --ext=.js,.yml . "$@"
else
  echo "eslint is not available. You may need to 'ddev exec \"cd $DDEV_DOCROOT/core && yarn install\"'"
  exit 1
fi
