#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/ddev/ddev-drupal-contrib
## Description: Run phpcbf inside the web container
## Usage: phpcbf [flags] [args]
## Example: "ddev phpcbf" or "ddev phpcbf -n"
## ExecRaw: true

set -eu -o pipefail

if ! command -v phpcbf >/dev/null; then
  echo "phpcbf is not available. You may need to 'ddev composer install'"
  exit 1
fi
cd "${DDEV_COMPOSER_ROOT}" || exit
phpcbf "$@"
