#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/ddev/ddev-drupal-contrib
## Description: Run stylelint inside the web container
## Usage: stylelint [flags] [args]
## Example: "ddev stylelint"
## ExecRaw: true

set -eu -o pipefail

if "$DDEV_DOCROOT/core/node_modules/.bin/stylelint" --version >/dev/null ; then
  # Change directory to the theme folder
  cd "${DDEV_COMPOSER_ROOT}/${THEME_PATH}" || exit
  "$DDEV_DOCROOT/core/node_modules/.bin/stylelint" --color --config "$DDEV_DOCROOT/core/.stylelintrc.json" "./**/*.css" "$@"
else
  echo "stylelint is not available. You may need to 'ddev exec \"cd $DDEV_DOCROOT/core && yarn install\"'"
  exit 1
fi
